package dev.olaore.hero_domain

data class Hero(
    val id: Int = 0,
    val localizedName: String = "Fouad Hero",
    val primaryAttribute: HeroAttribute = HeroAttribute.Intelligence,
    val attackType: HeroAttackType = HeroAttackType.Melee,
    val roles: List<HeroRole> = listOf(),
    val img: String = "",
    val icon: String = "",
    val baseHealth: Float = 0f,
    val baseHealthRegen: Float? = null,
    val baseMana: Float = 0f,
    val baseManaRegen: Float? = null,
    val baseArmor: Float = 0f,
    val baseMoveRate: Float = 0f,
    val baseAttackMin: Int = 0,
    val baseAttackMax: Int = 0,
    val baseStr: Int = 0,
    val baseAgi: Int = 0,
    val baseInt: Int = 0,
    val strGain: Float = 0f, // Strength gain per lvl
    val agiGain: Float = 0f, // Agility gain per lvl
    val intGain: Float = 0f, // Intelligence gain per lvl
    val attackRange: Int = 0,
    val projectileSpeed: Int = 0,
    val attackRate: Float = 0f,
    val moveSpeed: Int  = 0,
    val turnRate: Float? = 0F,
    val legs: Int = 0, // How many legs does this hero have?
    val turboPicks: Int = 0, // How many times picked for turbo matches?
    val turboWins: Int = 0, // How many times won a turbo match?
    val proWins: Int = 0, // How many times won a pro match?
    val proPick: Int = 0, // How many times picked in pro match?
    val firstPick: Int = 0, // How many times picked first?
    val firstWin: Int = 0, // How many times picked first and won?
    val secondPick: Int = 0, // How many times picked second?
    val secondWin: Int = 0, // How many times picked second and won?
    val thirdPick: Int = 0, // How many times picked third?
    val thirdWin: Int = 0, // How many times picked third and won?
    val fourthPick: Int = 0, // How many times picked in fourth round?
    val fourthWin: Int = 0, // How many times picked in fourth round and won?
    val fifthPick: Int = 0, // How many times picked fifth?
    val fifthWin: Int = 0, // How many times picked fifth and won?
    val sixthPick: Int = 0, // How many times picked sixth?
    val sixthWin: Int = 0, // How many times picked sixth and won?
    val seventhPick: Int = 0, // How many times picked seventh?
    val seventhWin: Int = 0, // How many times picked seventh and won?
    val eighthPick: Int = 0, // How many times picked eighth round?
    val eighthWin: Int = 0, // How many times picked eighth and won?
)